CONFIG = {
    "store_name": "Crochetial by Sadaf Muqeet",
    "whatsapp_number": "923330211028",
    "whatsapp_display": "+92-333-0211028",
    "email": "order@crochetial.shop",
    "currency_symbol": "Rs",
    "ship_karachi": 350,
    "ship_other": 450,
    "ship_global": 0,
}

CATEGORIES = [('all', 'All'),
 ('flowers', 'Flowers'),
 ('keychains', 'Keychains'),
 ('cardigans', 'Cardigans'),
 ('handmade-bags', 'Handmade Bags'),
 ('accessories', 'Accessories'),
 ('acrylic-yarn', 'Acrylic Yarn'),
 ('kids-set', 'Kids Set')]

CAFE_ITEMS = [{'title': 'Hot Coffee', 'description': 'Comforting freshly brewed homemade coffee.', 'price': 'Starting from Rs 450'},
 {'title': 'Cold Coffee',
  'description': 'Creamy chilled coffee prepared fresh on order.',
  'price': 'Starting from Rs 550'},
 {'title': 'Homemade Bakes',
  'description': 'Small-batch brownies, cookies, cakes and seasonal sweets.',
  'price': 'Price on request'},
 {'title': 'Bakery Savouries',
  'description': 'Fresh savoury snacks for tea-time, gifting trays and gatherings.',
  'price': 'Price on request'}]

PRODUCTS = [{'id': 'single-rose',
  'name': 'Single Rose',
  'category': 'flowers',
  'tags': ['single', 'flower'],
  'price': 1020,
  'image': 'https://i.postimg.cc/PxrPH1H3/Single-Rose.png',
  'images': ['https://i.postimg.cc/PxrPH1H3/Single-Rose.png', 'https://i.postimg.cc/KzfhRTzV/Rose-Front.png', 'https://i.postimg.cc/qR4dJwkY/Rose-Back.png'],
  'alt': 'Single crochet rose',
  'desc': 'A timeless single crochet rose, handcrafted with premium yarn. Perfect for gifting or home decor. Each petal is carefully stitched to create a '
          'lifelike bloom that lasts forever. Available in classic red or soft pink.',
  'sizes': ['One Size'],
  'colors': ['Red', 'Pink']},
 {'id': 'single-sunflower',
  'name': 'Single Sunflower',
  'category': 'flowers',
  'tags': ['single', 'flower'],
  'price': 1020,
  'image': 'https://i.postimg.cc/tTCYbFbc/sunflower.png',
  'images': ['https://i.postimg.cc/tTCYbFbc/sunflower.png',
             'https://i.postimg.cc/SRKF8KY9/Sunflower-Front.png',
             'https://i.postimg.cc/Y9RBhF0C/sunflower-Back.png'],
  'alt': 'Single crochet sunflower',
  'desc': 'Bring sunshine into any space with this cheerful crochet sunflower. Handmade with vibrant yellow yarn and detailed center. A perfect pick-me-up '
          'gift that never wilts. Brightens any room instantly.',
  'sizes': ['One Size'],
  'colors': ['Yellow']},
 {'id': 'single-lily',
  'name': 'Single Lily',
  'category': 'flowers',
  'tags': ['single', 'flower'],
  'price': 1020,
  'image': 'https://i.postimg.cc/nzptF2Hw/Lily-1.png',
  'images': ['https://i.postimg.cc/nzptF2Hw/Lily-1.png', 'https://i.postimg.cc/XJ40jLVK/Lily-Font.png', 'https://i.postimg.cc/CKjgpXVh/Lily-Back.png'],
  'alt': 'Single crochet lily',
  'desc': 'Delicate and graceful, this crochet lily captures the elegance of the real flower. Handcrafted with soft yarn and intricate detailing. Perfect for '
          'minimalist decor or as a thoughtful gift. Pure and timeless beauty.',
  'sizes': ['One Size'],
  'colors': ['White', 'Pink']},
 {'id': 'single-jasmine',
  'name': 'Single Jasmine',
  'category': 'flowers',
  'tags': ['single', 'flower'],
  'price': 1020,
  'image': 'https://i.postimg.cc/s2Fr8yb2/Jasmine.png',
  'images': ['https://i.postimg.cc/s2Fr8yb2/Jasmine.png', 'https://i.postimg.cc/xdK2VhSS/Jasmine-1.png', 'https://i.postimg.cc/8C8S3D9n/Jasmine-Back.png'],
  'alt': 'Single crochet jasmine',
  'desc': 'Sweet and simple, this crochet jasmine bloom brings fresh charm to any setting. Handmade with pristine white yarn and delicate petals. Symbolizes '
          'purity and grace. A lovely addition to your collection.',
  'sizes': ['One Size'],
  'colors': ['White']},
 {'id': 'single-wine-rose',
  'name': 'Single Wine Rose',
  'category': 'flowers',
  'tags': ['single', 'flower'],
  'price': 1020,
  'image': 'https://i.postimg.cc/T2kXxnB1/Wine-Rose.png',
  'images': ['https://i.postimg.cc/T2kXxnB1/Wine-Rose.png', 'https://i.postimg.cc/5ykcmM8Z/Wine-Rose-Flower.png'],
  'alt': 'Single crochet wine rose',
  'desc': 'Sophisticated and romantic, this deep wine-red crochet rose makes a bold statement. Handcrafted with rich burgundy yarn for an elegant look. '
          'Perfect for special occasions or as a unique gift. Timeless sophistication.',
  'sizes': ['One Size'],
  'colors': ['Wine Red']},
 {'id': 'single-tulip',
  'name': 'Single Tulip',
  'category': 'flowers',
  'tags': ['single', 'flower'],
  'price': 1020,
  'image': 'https://i.postimg.cc/rsY69L5J/Tulip.png',
  'images': ['https://i.postimg.cc/rsY69L5J/Tulip.png', 'https://i.postimg.cc/2y5Rv5Lx/Tulip-Back.png'],
  'alt': 'Single crochet tulip',
  'desc': "Elegant and colorful, this crochet tulip captures spring's beauty year-round. Handmade with vibrant yarn and realistic shape. Perfect for adding a "
          'pop of color to any space. Fresh and cheerful design.',
  'sizes': ['One Size'],
  'colors': ['Pink', 'Red', 'Yellow', 'Purple']},
 {'id': 'rose-bouquet',
  'name': 'Rose Bouquet',
  'category': 'flowers',
  'tags': ['bouquet', 'floral'],
  'price': 3000,
  'image': 'https://i.postimg.cc/4dsTfPJr/Rose-Bouqet.png',
  'images': ['https://i.postimg.cc/4dsTfPJr/Rose-Bouqet.png',
             'https://i.postimg.cc/1tB1fFtC/Rose-Bouqet-1.png',
             'https://i.postimg.cc/KzfhRTzV/Rose-Front.png',
             'https://i.postimg.cc/qR4dJwkY/Rose-Back.png'],
  'alt': 'Crochet rose bouquet',
  'desc': 'A stunning arrangement of handcrafted crochet roses that last forever. Each bouquet features 5-7 roses carefully arranged with green leaves. '
          'Perfect for weddings, anniversaries, or home decor. Choose from classic red or romantic pink. Never needs water!',
  'sizes': ['One Size'],
  'colors': ['Red', 'Pink']},
 {'id': 'sunflower-bouquet',
  'name': 'Sunflower Bouquet',
  'category': 'flowers',
  'tags': ['bouquet', 'floral'],
  'price': 3000,
  'image': 'https://i.postimg.cc/xdPcBtwb/Sunflower-Bouqet-2.jpg',
  'images': ['https://i.postimg.cc/xdPcBtwb/Sunflower-Bouqet-2.jpg',
             'https://i.postimg.cc/VNFd2Dxt/Sunflower-Bouqet-3.jpg',
             'https://i.postimg.cc/rmj2K4sD/Sunflower-Bouqet.png',
             'https://i.postimg.cc/j2j0Njns/Sunflower-Bouqet-1.png',
             'https://i.postimg.cc/SRKF8KY9/Sunflower-Front.png',
             'https://i.postimg.cc/Y9RBhF0C/sunflower-Back.png'],
  'alt': 'Crochet sunflower bouquet',
  'desc': 'Brighten any room with this cheerful sunflower bouquet. Features 5-7 handcrafted sunflowers with detailed centers and vibrant yellow petals. '
          'Perfect for bringing summer vibes all year round. Makes a joyful gift that never fades. Sunshine in a bouquet!',
  'sizes': ['One Size'],
  'colors': ['Yellow']},
 {'id': 'lily-bouquet',
  'name': 'Lily Bouquet',
  'category': 'flowers',
  'tags': ['bouquet', 'floral'],
  'price': 3000,
  'image': 'https://i.postimg.cc/MGySJN8b/Lily-Bouqet.png',
  'images': ['https://i.postimg.cc/MGySJN8b/Lily-Bouqet.png',
             'https://i.postimg.cc/mDBGLjbF/Lily-Bouqet-1.png',
             'https://i.postimg.cc/XJ40jLVK/Lily-Font.png',
             'https://i.postimg.cc/CKjgpXVh/Lily-Back.png'],
  'alt': 'Crochet lily bouquet',
  'desc': 'Elegant and timeless, this lily bouquet showcases the beauty of handcrafted blooms. Features 5-7 delicate lilies with intricate petal work. Perfect '
          'for sophisticated decor or special occasions. Available in pure white or soft pink. Grace and elegance combined.',
  'sizes': ['One Size'],
  'colors': ['White', 'Pink']},
 {'id': 'jasmine-bouquet',
  'name': 'Jasmine Bouquet',
  'category': 'flowers',
  'tags': ['bouquet', 'floral'],
  'price': 3000,
  'image': 'https://i.postimg.cc/XvMbh3tW/Jasmine-Bouqet.png',
  'images': ['https://i.postimg.cc/XvMbh3tW/Jasmine-Bouqet.png',
             'https://i.postimg.cc/SK0h5qHs/Jasmine-Bouqet-1.png',
             'https://i.postimg.cc/s2Fr8yb2/Jasmine.png',
             'https://i.postimg.cc/8C8S3D9n/Jasmine-Back.png'],
  'alt': 'Crochet jasmine bouquet',
  'desc': 'Sweet and fragrant-looking, this jasmine bouquet brings fresh charm to any space. Features multiple delicate white blooms arranged beautifully. '
          'Perfect for minimalist or romantic decor. Symbolizes purity and love. A thoughtful, lasting gift.',
  'sizes': ['One Size'],
  'colors': ['White']},
 {'id': 'wine-rose-bouquet',
  'name': 'Wine Rose Bouquet',
  'category': 'flowers',
  'tags': ['bouquet', 'floral'],
  'price': 3000,
  'image': 'https://i.postimg.cc/5ykcmM8R/Wine-Rose-Bouqet.png',
  'images': ['https://i.postimg.cc/5ykcmM8R/Wine-Rose-Bouqet.png',
             'https://i.postimg.cc/x8FrPSLp/Wine-Rose-Bouqet-1.png',
             'https://i.postimg.cc/T2kXxnB1/Wine-Rose.png',
             'https://i.postimg.cc/5ykcmM8Z/Wine-Rose-Flower.png'],
  'alt': 'Crochet wine rose bouquet',
  'desc': 'Sophisticated and romantic, this wine rose bouquet features deep burgundy blooms. Each bouquet includes 5-7 handcrafted roses with rich color. '
          'Perfect for elegant events, romantic gifts, or luxury home decor. Bold and beautiful statement piece.',
  'sizes': ['One Size'],
  'colors': ['Wine Red']},
 {'id': 'tulip-bouquet',
  'name': 'Tulip Bouquet',
  'category': 'flowers',
  'tags': ['bouquet', 'floral'],
  'price': 3000,
  'image': 'https://i.postimg.cc/GtpwYpTz/Tulip-Bouqet.png',
  'images': ['https://i.postimg.cc/GtpwYpTz/Tulip-Bouqet.png',
             'https://i.postimg.cc/0jHgCq7Y/Tulip-Bouqet-1.png',
             'https://i.postimg.cc/rsY69L5J/Tulip.png',
             'https://i.postimg.cc/2y5Rv5Lx/Tulip-Back.png'],
  'alt': 'Crochet tulip bouquet',
  'desc': 'Vibrant and elegant, this tulip bouquet brings spring beauty all year round. Features 5-7 handcrafted tulips with realistic shape and vibrant '
          'colors. Perfect for adding a cheerful pop of color to any space. Available in multiple colors. Fresh and delightful arrangement.',
  'sizes': ['One Size'],
  'colors': ['Pink', 'Red', 'Yellow', 'Purple']},
 {'id': 'customized-flowers',
  'name': 'Customized Flowers',
  'category': 'flowers',
  'tags': ['custom', 'flower'],
  'price': 1200,
  'image': 'https://i.postimg.cc/Nj2tpLJ5/Customization-Flowers.png',
  'images': ['https://i.postimg.cc/Nj2tpLJ5/Customization-Flowers.png'],
  'alt': 'Customized crochet flowers',
  'desc': 'Create your perfect flower! Choose your favorite flower type, colors, and style. Handcrafted with premium yarn according to your specifications. '
          'Perfect for personalized gifts or unique decor. Mention your customization details in the order notes. Let your creativity bloom!',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'customized-bouquet',
  'name': 'Customized Bouquet',
  'category': 'flowers',
  'tags': ['custom', 'bouquet'],
  'price': 3600,
  'image': 'https://i.postimg.cc/x1NQtqxR/Flowers-Bouqet-Customized.png',
  'images': ['https://i.postimg.cc/x1NQtqxR/Flowers-Bouqet-Customized.png', 'https://i.postimg.cc/MpfwdXP9/Flowers-Bouqet-Customized-1.png'],
  'alt': 'Customized crochet bouquet',
  'desc': 'Design your dream bouquet! Choose your favorite flowers, colors, and arrangement style. Each bouquet is handcrafted with 5-7 blooms according to '
          'your specifications. Perfect for special occasions or personalized gifts. Mention your customization details in the order notes. Your vision, our '
          'craftsmanship!',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'key-rose',
  'name': 'Rose Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'flower'],
  'price': 720,
  'image': 'https://i.postimg.cc/MTVSd3zF/Rose-Keychain.png',
  'images': ['https://i.postimg.cc/MTVSd3zF/Rose-Keychain.png',
             'https://i.postimg.cc/fLmNBqMC/Rose-Keychain-Back.png',
             'https://i.postimg.cc/G2GCqgbq/Rose-Keychain-Front.png'],
  'alt': 'Crochet rose keychain',
  'desc': 'Petite crochet rose charm for your keys or bag.',
  'sizes': ['One Size'],
  'colors': ['Red', 'Pink']},
 {'id': 'key-sunflower',
  'name': 'Sunflower Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'flower'],
  'price': 720,
  'image': 'https://i.postimg.cc/Hstykf8M/Sunflower-Keychain-Real.jpg',
  'images': ['https://i.postimg.cc/Hstykf8M/Sunflower-Keychain-Real.jpg',
             'https://i.postimg.cc/SR4p5LKv/Sunflower-Keychain.png',
             'https://i.postimg.cc/ZRpSVsJX/Sunflower-Keychain-Back.png',
             'https://i.postimg.cc/HnmCK0LZ/Sunflower-Keychain-Front.png'],
  'alt': 'Crochet sunflower keychain',
  'desc': 'A cheerful sunflower keychain â\x80\x94 tiny sunshine.',
  'sizes': ['One Size'],
  'colors': ['Yellow']},
 {'id': 'key-wine-rose',
  'name': 'Wine Rose Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'flower'],
  'price': 720,
  'image': 'https://i.postimg.cc/PJHkcbxq/Wine-Rose-Keychain.png',
  'images': ['https://i.postimg.cc/PJHkcbxq/Wine-Rose-Keychain.png',
             'https://i.postimg.cc/ZnmhgPRR/Wine-Rose-Keychain-Back.png',
             'https://i.postimg.cc/6qKNSV35/Wine-Rose-Keychain-Front.png'],
  'alt': 'Crochet wine rose keychain',
  'desc': 'Elegant wine-red crochet rose in mini form.',
  'sizes': ['One Size'],
  'colors': ['Wine Red']},
 {'id': 'key-lily',
  'name': 'Lily Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'flower'],
  'price': 720,
  'image': 'https://i.postimg.cc/yNwKhCCz/Lily-Keychain.png',
  'images': ['https://i.postimg.cc/yNwKhCCz/Lily-Keychain.png',
             'https://i.postimg.cc/7LCDTYdP/Lily-Keychain-Back.png',
             'https://i.postimg.cc/rpvTG2Xv/Lily-Keychain-Front.png'],
  'alt': 'Crochet lily keychain',
  'desc': 'Delicate crochet lily to carry everywhere.',
  'sizes': ['One Size'],
  'colors': ['White', 'Pink']},
 {'id': 'key-jasmine',
  'name': 'Jasmine Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'flower'],
  'price': 720,
  'image': 'https://i.postimg.cc/pd9xnX4v/Jasmine-Keychain.png',
  'images': ['https://i.postimg.cc/pd9xnX4v/Jasmine-Keychain.png',
             'https://i.postimg.cc/rpdctFbP/Jasmine-Keychain-Back.png',
             'https://i.postimg.cc/MGcxjK4h/Jasmine-Keychain-Front.png'],
  'alt': 'Crochet jasmine keychain',
  'desc': 'Sweet jasmine charm â\x80\x94 simple and fresh.',
  'sizes': ['One Size'],
  'colors': ['White']},
 {'id': 'key-tulip',
  'name': 'Tulip Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'flower'],
  'price': 720,
  'image': 'https://i.postimg.cc/Rhmz81Fm/Tulip-Keychain.png',
  'images': ['https://i.postimg.cc/Rhmz81Fm/Tulip-Keychain.png',
             'https://i.postimg.cc/kGCdZN4P/Tulip-Keychain-Back.png',
             'https://i.postimg.cc/prvt7QTt/Tulip-Keychain-Front.png'],
  'alt': 'Crochet tulip keychain',
  'desc': 'Beautiful tulip charm â\x80\x94 elegant and colorful.',
  'sizes': ['One Size'],
  'colors': ['Pink', 'Red', 'Yellow']},
 {'id': 'key-bear',
  'name': 'Bear Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'bear', 'plush'],
  'price': 720,
  'image': 'https://i.postimg.cc/fRqDL0Hc/Bear-Keychain.png',
  'images': ['https://i.postimg.cc/fRqDL0Hc/Bear-Keychain.png',
             'https://i.postimg.cc/Sx1kszZx/Bear-Keychain-Back.png',
             'https://i.postimg.cc/CxrS1fvq/Bear-Keychain-Front.png'],
  'alt': 'Crochet bear keychain',
  'desc': 'Adorable mini bear keychain â\x80\x94 cute cuddle buddy for your keys.',
  'sizes': ['One Size'],
  'colors': ['Brown', 'Beige', 'Cream']},
 {'id': 'key-panda',
  'name': 'Panda Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'panda', 'plush'],
  'price': 720,
  'image': 'https://i.postimg.cc/FK2vbXX9/Panda-Keychain.png',
  'images': ['https://i.postimg.cc/FK2vbXX9/Panda-Keychain.png',
             'https://i.postimg.cc/N0Wt8vvt/Panda-Keychain-Back.png',
             'https://i.postimg.cc/3wPhjQQ7/Panda-Keychain-Front.png'],
  'alt': 'Crochet panda keychain',
  'desc': 'Cute mini panda keychain â\x80\x94 black & white charm.',
  'sizes': ['One Size'],
  'colors': ['Black/White']},
 {'id': 'key-polar',
  'name': 'Polar Bear Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'polar-bear', 'plush'],
  'price': 720,
  'image': 'https://i.postimg.cc/DZLTBp7q/Polar-Keychain.png',
  'images': ['https://i.postimg.cc/DZLTBp7q/Polar-Keychain.png',
             'https://i.postimg.cc/PqBHbnnx/Polar-Keychain-Back.png',
             'https://i.postimg.cc/k5kCNPP8/Polar-Keychain-Front.png'],
  'alt': 'Crochet polar bear keychain',
  'desc': 'Adorable white polar bear keychain â\x80\x94 tiny warm hugs.',
  'sizes': ['One Size'],
  'colors': ['White']},
 {'id': 'key-custom',
  'name': 'Customized Flower Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'custom', 'flower'],
  'price': 1150,
  'image': 'https://i.postimg.cc/cL48gXft/Custom-Keychain.jpg',
  'images': ['https://i.postimg.cc/cL48gXft/Custom-Keychain.jpg',
             'https://i.postimg.cc/8Pb6zqfL/Custom-Keychain-Bow.jpg',
             'https://i.postimg.cc/52NFYn8C/Custom-Keychain-Cherry.jpg',
             'https://i.postimg.cc/T375rgc9/Tulip-Keychain-Real.jpg'],
  'alt': 'Custom crochet flower keychain',
  'desc': 'Pick your flower/colors â\x80\x94 mention details in Order notes.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'key-custom-bear',
  'name': 'Customized Bear Keychain',
  'category': 'keychains',
  'tags': ['keychain', 'custom', 'bear'],
  'price': 1150,
  'image': 'https://i.postimg.cc/CxrS1fvZ/Bear-Keychain-Customized.png',
  'images': ['https://i.postimg.cc/CxrS1fvZ/Bear-Keychain-Customized.png',
             'https://i.postimg.cc/htZcj7CQ/Bear-Keychain-Customized-Back.png',
             'https://i.postimg.cc/nhSpzQdX/Bear-Keychain-Customized-Front.png'],
  'alt': 'Custom crochet bear keychain',
  'desc': 'Customize your bear keychain â\x80\x94 pick colors and style. Mention details in Order notes.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'yarn-black',
  'name': 'Black Yarn',
  'category': 'acrylic-yarn',
  'tags': ['yarn', 'black'],
  'price': 360,
  'image': 'https://i.postimg.cc/qqMgH9NP/Black-Yarn-1.png',
  'images': ['https://i.postimg.cc/qqMgH9NP/Black-Yarn-1.png', 'https://i.postimg.cc/J44HGfB5/Black-Yarn.png'],
  'alt': 'Black yarn for crochet',
  'desc': 'Premium quality black yarn perfect for crochet projects. Soft, durable, and versatile for any design.',
  'sizes': ['One Size'],
  'colors': ['Black']},
 {'id': 'yarn-brown',
  'name': 'Brown Yarn',
  'category': 'acrylic-yarn',
  'tags': ['yarn', 'brown'],
  'price': 360,
  'image': 'https://i.postimg.cc/gjkrbfwb/Brown-Yarn-1.png',
  'images': ['https://i.postimg.cc/gjkrbfwb/Brown-Yarn-1.png', 'https://i.postimg.cc/3JJ0dsDL/Brown-Yarn.png'],
  'alt': 'Brown yarn for crochet',
  'desc': 'Rich brown yarn ideal for warm, earthy crochet creations. Soft texture and excellent quality.',
  'sizes': ['One Size'],
  'colors': ['Brown']},
 {'id': 'yarn-pink',
  'name': 'Pink Yarn',
  'category': 'acrylic-yarn',
  'tags': ['yarn', 'pink'],
  'price': 360,
  'image': 'https://i.postimg.cc/cC46GVvV/Pink-Yarn-1.png',
  'images': ['https://i.postimg.cc/cC46GVvV/Pink-Yarn-1.png', 'https://i.postimg.cc/155VfkNK/Pink-Yarn.png'],
  'alt': 'Pink yarn for crochet',
  'desc': 'Beautiful pink yarn perfect for delicate and feminine crochet projects. Soft and easy to work with.',
  'sizes': ['One Size'],
  'colors': ['Pink']},
 {'id': 'yarn-purple',
  'name': 'Purple Yarn',
  'category': 'acrylic-yarn',
  'tags': ['yarn', 'purple'],
  'price': 360,
  'image': 'https://i.postimg.cc/C5LdpWZy/Purple-Yarn-1.png',
  'images': ['https://i.postimg.cc/C5LdpWZy/Purple-Yarn-1.png', 'https://i.postimg.cc/Hss8Vq72/Purple-Yarn.png'],
  'alt': 'Purple yarn for crochet',
  'desc': 'Vibrant purple yarn for creative crochet designs. High-quality and colorfast.',
  'sizes': ['One Size'],
  'colors': ['Purple']},
 {'id': 'yarn-red',
  'name': 'Red Yarn',
  'category': 'acrylic-yarn',
  'tags': ['yarn', 'red'],
  'price': 360,
  'image': 'https://i.postimg.cc/Hnsj1fJY/Red-Yarn-1.png',
  'images': ['https://i.postimg.cc/Hnsj1fJY/Red-Yarn-1.png', 'https://i.postimg.cc/jdgwNMHV/Velvet-Red-Yarn.png'],
  'alt': 'Red yarn for crochet',
  'desc': 'Bold red yarn perfect for eye-catching crochet projects. Durable and vibrant color.',
  'sizes': ['One Size'],
  'colors': ['Red']},
 {'id': 'yarn-velvet-red',
  'name': 'Velvet Red Yarn',
  'category': 'acrylic-yarn',
  'tags': ['yarn', 'velvet', 'red', 'premium'],
  'price': 360,
  'image': 'https://i.postimg.cc/RhVqxj3q/Velvet-Red-Yarn-1.png',
  'images': ['https://i.postimg.cc/RhVqxj3q/Velvet-Red-Yarn-1.png', 'https://i.postimg.cc/jdgwNMHV/Velvet-Red-Yarn.png'],
  'alt': 'Velvet red yarn for crochet',
  'desc': 'Luxurious velvet red yarn with ultra-soft texture. Perfect for plush toys and premium accessories.',
  'sizes': ['One Size'],
  'colors': ['Red']},
 {'id': 'yarn-white',
  'name': 'White Yarn',
  'category': 'acrylic-yarn',
  'tags': ['yarn', 'white'],
  'price': 360,
  'image': 'https://i.postimg.cc/YqnGgd6w/White-Yarn.png',
  'images': ['https://i.postimg.cc/YqnGgd6w/White-Yarn.png', 'https://i.postimg.cc/XqHqjQFb/White-Yarn-1.png'],
  'alt': 'White yarn for crochet',
  'desc': 'Pure white yarn ideal for classic and elegant crochet projects. Soft, clean, and versatile.',
  'sizes': ['One Size'],
  'colors': ['White']},
 {'id': 'gajras-pair',
  'name': 'Gajras Pair',
  'category': 'accessories',
  'tags': ['gajras', 'hair', 'traditional'],
  'price': 1300,
  'image': 'https://i.postimg.cc/T2nPpLtJ/Gajras-Pair.jpg',
  'images': ['https://i.postimg.cc/T2nPpLtJ/Gajras-Pair.jpg',
             'https://i.postimg.cc/7PSLfGKR/Gajras-Pair-1.jpg',
             'https://i.postimg.cc/L4jsnYx7/Gajras-Pair-2.jpg',
             'https://i.postimg.cc/9XyfrRLs/Gajras-Pair-3.jpg'],
  'alt': 'Handmade crochet gajras pair',
  'desc': 'Beautiful handmade crochet gajras pair perfect for traditional occasions. Crafted with premium yarn in elegant floral design. Lightweight and '
          'comfortable to wear. Perfect for weddings, festivals, or cultural celebrations. Adds a traditional touch to any outfit. Comes as a pair for both '
          'sides.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'bunny-amigurumi',
  'name': 'Bunny Amigurumi',
  'category': 'accessories',
  'tags': ['amigurumi', 'bunny', 'toy', 'handmade'],
  'price': 5040,
  'image': 'https://i.postimg.cc/y60NkgLj/Bunny-Amigurumi.jpg',
  'images': ['https://i.postimg.cc/y60NkgLj/Bunny-Amigurumi.jpg',
             'https://i.postimg.cc/RCw0N6gT/Bunny-Amigurumi-1.jpg',
             'https://i.postimg.cc/44p3m7WW/Bunny-Amigurumi-2.jpg'],
  'alt': 'Handmade bunny amigurumi',
  'desc': 'Adorable handmade bunny amigurumi crafted with love and care. Made with soft, premium yarn perfect for cuddling. Features cute bunny design with '
          'detailed features. Safe for children and makes an excellent gift. Perfect companion for kids or decorative piece for collectors. Unique handmade '
          'quality with attention to every detail.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'crochet-bandana',
  'name': 'Crochet Custom Bandana',
  'category': 'accessories',
  'tags': ['bandana', 'custom', 'handmade', 'hair'],
  'price': 1200,
  'image': 'https://i.postimg.cc/4NwR2dtS/Bandana.jpg',
  'images': ['https://i.postimg.cc/4NwR2dtS/Bandana.jpg', 'https://i.postimg.cc/ncTfSz7W/Bandana-1.jpg'],
  'alt': 'Crochet custom bandana',
  'desc': 'Handmade crochet bandana crafted with premium yarn. Stylish and versatile accessory perfect for any occasion. Customizable in your choice of colors '
          'and patterns. Lightweight and comfortable to wear. Perfect for festivals, casual outings, or as a unique fashion statement. Each piece is uniquely '
          'handcrafted with care.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'crochet-flower-pouches',
  'name': 'Crochet Flower Pouches',
  'category': 'accessories',
  'tags': ['pouch', 'flower', 'handmade', 'bag'],
  'price': 720,
  'image': 'https://i.postimg.cc/mghsJHQy/Crochet-Flower-Pouches.jpg',
  'images': ['https://i.postimg.cc/mghsJHQy/Crochet-Flower-Pouches.jpg',
             'https://i.postimg.cc/Vk58pCjR/Crochet-Flower-Pouches-1.jpg',
             'https://i.postimg.cc/DwmTHXqQ/Crochet-Flower-Pouches-Black.jpg',
             'https://i.postimg.cc/cL6S2nQQ/Crochet-Flower-Pouches-White.jpg'],
  'alt': 'Crochet flower pouches',
  'desc': 'Adorable handmade crochet flower pouches perfect for storing small essentials. Beautifully crafted with floral details and premium yarn. Available '
          'in multiple colors including black and white. Lightweight and compact â\x80\x94 ideal for coins, earrings, or small accessories. A charming '
          'handmade gift for any occasion.',
  'sizes': ['One Size'],
  'colors': ['Black', 'White', 'Custom']},
 {'id': 'crochet-tiny-pouches',
  'name': 'Crochet Tiny Pouches',
  'category': 'accessories',
  'tags': ['pouch', 'tiny', 'handmade', 'bag'],
  'price': 720,
  'image': 'https://i.postimg.cc/13TQQ3H2/Crochet-Tiny-Pouches.jpg',
  'images': ['https://i.postimg.cc/13TQQ3H2/Crochet-Tiny-Pouches.jpg',
             'https://i.postimg.cc/rwzk3rSb/Crochet-Tiny-Pouches-Closeup.jpg',
             'https://i.postimg.cc/W1Kvv1n8/Crochet-Tiny-Pouches-Pink.jpg',
             'https://i.postimg.cc/T3S6639S/Crochet-Tiny-Pouches-Purple.jpg'],
  'alt': 'Crochet tiny pouches',
  'desc': 'Sweet and compact handmade crochet tiny pouches. Perfect for carrying small items like coins, lip balm, or jewellery. Available in lovely pink and '
          'purple colors. Crafted with soft premium yarn and secure closure. A cute and practical accessory that makes a wonderful gift.',
  'sizes': ['One Size'],
  'colors': ['Pink', 'Purple']},
 {'id': 'black-laptop-cover',
  'name': 'Black Laptop Cover',
  'category': 'accessories',
  'tags': ['laptop-cover', 'black'],
  'price': 3000,
  'image': 'https://i.postimg.cc/m2xVvsPw/Black-Laptop-Cover.png',
  'images': ['https://i.postimg.cc/m2xVvsPw/Black-Laptop-Cover.png', 'https://i.postimg.cc/m2xVvsPw/Black-Laptop-Cover.png'],
  'alt': 'Black laptop cover',
  'desc': 'Stylish black laptop cover with premium protection. Handcrafted with durable materials to keep your laptop safe from scratches and dust. Features '
          'secure closure and comfortable carrying handle. Perfect for professionals and students. Sleek design meets practical functionality. Contact for '
          'customized sizes.',
  'sizes': ['One Size'],
  'colors': ['Black']},
 {'id': 'white-laptop-cover',
  'name': 'White Laptop Cover',
  'category': 'accessories',
  'tags': ['laptop-cover', 'white'],
  'price': 3000,
  'image': 'https://i.postimg.cc/c4qTpSvj/White-Laptop-Cover.png',
  'images': ['https://i.postimg.cc/c4qTpSvj/White-Laptop-Cover.png', 'https://i.postimg.cc/c4qTpSvj/White-Laptop-Cover.png'],
  'alt': 'White laptop cover',
  'desc': 'Clean white laptop cover with elegant design. Handcrafted protection for your valuable laptop. Made with high-quality materials for long-lasting '
          'durability. Features secure zip closure and padded interior. Perfect for maintaining a professional appearance while protecting your device. '
          'Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['White']},
 {'id': 'green-black-laptop-cover',
  'name': 'Green Black Laptop Cover',
  'category': 'accessories',
  'tags': ['laptop-cover', 'green', 'black'],
  'price': 3000,
  'image': 'https://i.postimg.cc/02gZTszn/Green-Black-Laptop-Cover.png',
  'images': ['https://i.postimg.cc/02gZTszn/Green-Black-Laptop-Cover.png', 'https://i.postimg.cc/02gZTszn/Green-Black-Laptop-Cover.png'],
  'alt': 'Green black laptop cover',
  'desc': 'Unique green and black laptop cover with modern design. Handcrafted with premium materials for superior protection. Features stylish color '
          'combination and secure closure. Perfect for those who want to stand out while keeping their laptop safe. Durable and fashionable. Contact for '
          'customized sizes.',
  'sizes': ['One Size'],
  'colors': ['Green/Black']},
 {'id': 'white-black-laptop-cover',
  'name': 'White Black Laptop Cover',
  'category': 'accessories',
  'tags': ['laptop-cover', 'white', 'black'],
  'price': 3000,
  'image': 'https://i.postimg.cc/4NCwDgYv/White-Black-Laptop-Cover.png',
  'images': ['https://i.postimg.cc/4NCwDgYv/White-Black-Laptop-Cover.png', 'https://i.postimg.cc/4NCwDgYv/White-Black-Laptop-Cover.png'],
  'alt': 'White black laptop cover',
  'desc': 'Sophisticated white and black laptop cover with classic design. Handcrafted protection with timeless color combination. Features secure closure and '
          'comfortable grip. Perfect for business professionals and students alike. Elegant style with practical protection. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['White/Black']},
 {'id': 'customized-laptop-cover',
  'name': 'Customized Laptop Cover',
  'category': 'accessories',
  'tags': ['laptop-cover', 'custom'],
  'price': 3000,
  'image': 'https://i.postimg.cc/vHRXJs4L/Customized-Laptop-Cover.png',
  'images': ['https://i.postimg.cc/vHRXJs4L/Customized-Laptop-Cover.png', 'https://i.postimg.cc/vHRXJs4L/Customized-Laptop-Cover.png'],
  'alt': 'Customized laptop cover',
  'desc': 'Personalized laptop cover made to your specifications. Choose your favorite colors, patterns, and design elements. Handcrafted with premium '
          'materials for optimal protection. Perfect for expressing your unique style while keeping your laptop safe. Mention customization details in order '
          'notes.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'brown-kids-set',
  'name': 'Brown Kids Set',
  'category': 'kids-set',
  'tags': ['kids-set', 'brown', 'children'],
  'price': 7200,
  'image': 'https://i.postimg.cc/hPvrJYn7/Kids-Set-Brown.png',
  'images': ['https://i.postimg.cc/hPvrJYn7/Kids-Set-Brown.png', 'https://i.postimg.cc/hPvrJYn7/Kids-Set-Brown.png'],
  'alt': 'Brown kids crochet set',
  'desc': 'Complete brown kids crochet set perfect for little ones. Handcrafted with soft, child-safe materials. Includes multiple pieces for a coordinated '
          'look. Perfect for special occasions, photoshoots, or everyday wear. Comfortable and adorable design that kids will love. Contact for customized '
          'sizes.',
  'sizes': ['One Size'],
  'colors': ['Brown']},
 {'id': 'pink-kids-set',
  'name': 'Pink Kids Set',
  'category': 'kids-set',
  'tags': ['kids-set', 'pink', 'children'],
  'price': 7200,
  'image': 'https://i.postimg.cc/tCJ51cbn/Kids-Set-Pink.png',
  'images': ['https://i.postimg.cc/tCJ51cbn/Kids-Set-Pink.png', 'https://i.postimg.cc/tCJ51cbn/Kids-Set-Pink.png'],
  'alt': 'Pink kids crochet set',
  'desc': 'Adorable pink kids crochet set designed for little princesses. Handmade with premium soft yarn for comfort and style. Complete coordinated outfit '
          'perfect for parties, special events, or daily wear. Sweet and charming design that brings joy to any occasion. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['Pink']},
 {'id': 'purple-kids-set',
  'name': 'Purple Kids Set',
  'category': 'kids-set',
  'tags': ['kids-set', 'purple', 'children'],
  'price': 7200,
  'image': 'https://i.postimg.cc/tCJ51cb1/Kids-Set-Purple.png',
  'images': ['https://i.postimg.cc/tCJ51cb1/Kids-Set-Purple.png', 'https://i.postimg.cc/tCJ51cb1/Kids-Set-Purple.png'],
  'alt': 'Purple kids crochet set',
  'desc': 'Beautiful purple kids crochet set with elegant design. Handcrafted with care using soft, breathable yarn. Complete outfit set perfect for special '
          'occasions and everyday adventures. Comfortable fit and stunning color that kids absolutely love. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['Purple']},
 {'id': 'watermelon-kids-set',
  'name': 'Watermelon Kids Set',
  'category': 'kids-set',
  'tags': ['kids-set', 'watermelon', 'children'],
  'price': 7200,
  'image': 'https://i.postimg.cc/hPvrJYnf/Kids-Set-Watermelon.png',
  'images': ['https://i.postimg.cc/hPvrJYnf/Kids-Set-Watermelon.png', 'https://i.postimg.cc/hPvrJYnf/Kids-Set-Watermelon.png'],
  'alt': 'Watermelon kids crochet set',
  'desc': 'Fun watermelon-themed kids crochet set with vibrant colors. Handmade with love using premium child-safe materials. Unique and playful design '
          'perfect for summer outings and special events. Comfortable and eye-catching outfit that brings smiles everywhere. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['Watermelon']},
 {'id': 'white-kids-set',
  'name': 'White Kids Set',
  'category': 'kids-set',
  'tags': ['kids-set', 'white', 'children'],
  'price': 7200,
  'image': 'https://i.postimg.cc/8PYbLbkY/Kids-Set-White.png',
  'images': ['https://i.postimg.cc/8PYbLbkY/Kids-Set-White.png', 'https://i.postimg.cc/8PYbLbkY/Kids-Set-White.png'],
  'alt': 'White kids crochet set',
  'desc': 'Classic white kids crochet set with timeless elegance. Handcrafted with premium soft yarn for ultimate comfort. Perfect for formal occasions, '
          'baptisms, or special celebrations. Pure and beautiful design that never goes out of style. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['White']},
 {'id': 'white-black-kids-set',
  'name': 'White Black Kids Set',
  'category': 'kids-set',
  'tags': ['kids-set', 'white', 'black', 'children'],
  'price': 7200,
  'image': 'https://i.postimg.cc/pXSBKBV1/Kids-Set-White-Black.png',
  'images': ['https://i.postimg.cc/pXSBKBV1/Kids-Set-White-Black.png', 'https://i.postimg.cc/pXSBKBV1/Kids-Set-White-Black.png'],
  'alt': 'White black kids crochet set',
  'desc': 'Sophisticated white and black kids crochet set with modern appeal. Handmade with attention to detail using premium materials. Stylish color '
          'combination perfect for formal events and special occasions. Comfortable and fashionable design for trendy little ones. Contact for customized '
          'sizes.',
  'sizes': ['One Size'],
  'colors': ['White/Black']},
 {'id': 'black-kids-short',
  'name': 'Kids Short Black',
  'category': 'kids-set',
  'tags': ['kids-set', 'kids-short', 'black', 'children'],
  'price': 6480,
  'image': 'https://i.postimg.cc/kMs87y9C/Kids-short-set-Black.png',
  'images': ['https://i.postimg.cc/BZpDJCsS/Kids-short-set-Banner.png', 'https://i.postimg.cc/kMs87y9C/Kids-short-set-Black.png'],
  'alt': 'Black kids short set',
  'desc': 'Stylish black kids short set perfect for warm weather. Handcrafted with soft, breathable materials for maximum comfort. Includes coordinated top '
          'and shorts for a complete look. Perfect for summer outings, playtime, or casual wear. Comfortable and trendy design. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['Black']},
 {'id': 'brown-kids-short',
  'name': 'Kids Short Brown',
  'category': 'kids-set',
  'tags': ['kids-set', 'kids-short', 'brown', 'children'],
  'price': 6480,
  'image': 'https://i.postimg.cc/ncLmrQcn/Kids-short-set-Brown.png',
  'images': ['https://i.postimg.cc/BZpDJCsS/Kids-short-set-Banner.png', 'https://i.postimg.cc/ncLmrQcn/Kids-short-set-Brown.png'],
  'alt': 'Brown kids short set',
  'desc': 'Warm brown kids short set with earthy charm. Handmade with premium soft yarn for comfort. Coordinated outfit perfect for casual outings and '
          'playtime. Breathable and comfortable for active kids. Adorable design in a versatile brown shade. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['Brown']},
 {'id': 'peach-kids-short',
  'name': 'Kids Short Peach',
  'category': 'kids-set',
  'tags': ['kids-set', 'kids-short', 'peach', 'children'],
  'price': 6480,
  'image': 'https://i.postimg.cc/PrqDJ8rC/Kids-short-set-Peach.png',
  'images': ['https://i.postimg.cc/BZpDJCsS/Kids-short-set-Banner.png', 'https://i.postimg.cc/PrqDJ8rC/Kids-short-set-Peach.png'],
  'alt': 'Peach kids short set',
  'desc': 'Sweet peach kids short set with soft, lovely color. Handcrafted with gentle materials perfect for sensitive skin. Complete coordinated look for '
          'summer fun. Comfortable and breathable for all-day wear. Charming design that kids will love. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['Peach']},
 {'id': 'purple-kids-short',
  'name': 'Kids Short Purple',
  'category': 'kids-set',
  'tags': ['kids-set', 'kids-short', 'purple', 'children'],
  'price': 6480,
  'image': 'https://i.postimg.cc/c45nn4rR/Kids-short-set-Purple.png',
  'images': ['https://i.postimg.cc/BZpDJCsS/Kids-short-set-Banner.png', 'https://i.postimg.cc/c45nn4rR/Kids-short-set-Purple.png'],
  'alt': 'Purple kids short set',
  'desc': 'Vibrant purple kids short set with fun, playful style. Handmade with soft, comfortable materials. Coordinated top and shorts perfect for active '
          'play. Breathable and easy to wear for summer adventures. Eye-catching design in a beautiful purple shade. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['Purple']},
 {'id': 'white-kids-short',
  'name': 'Kids Short White',
  'category': 'kids-set',
  'tags': ['kids-set', 'kids-short', 'white', 'children'],
  'price': 6480,
  'image': 'https://i.postimg.cc/tCmxxCY1/Kids-short-set-White.png',
  'images': ['https://i.postimg.cc/BZpDJCsS/Kids-short-set-Banner.png', 'https://i.postimg.cc/tCmxxCY1/Kids-short-set-White.png'],
  'alt': 'White kids short set',
  'desc': 'Classic white kids short set with timeless appeal. Handcrafted with premium soft materials for comfort. Clean and fresh look perfect for any '
          'occasion. Breathable and comfortable for warm weather. Versatile design that pairs with everything. Contact for customized sizes.',
  'sizes': ['One Size'],
  'colors': ['White']},
 {'id': 'short-sleeve-cardigan',
  'name': 'Short Sleeve Crochet Cardigan',
  'category': 'cardigans',
  'tags': ['cardigan', 'short sleeve', 'ladies'],
  'price': 8640,
  'image': 'https://i.postimg.cc/3xcZMkGW/Crochet-Short-Sleeves-Cardigan.png',
  'images': ['https://i.postimg.cc/3xcZMkGW/Crochet-Short-Sleeves-Cardigan.png',
             'https://i.postimg.cc/L8XV0tJY/Crochet-Short-Sleeves-Cardigan-Back.png',
             'https://i.postimg.cc/sgXJ0YMB/Crochet-Short-Sleeves-Cardigan-Close.png'],
  'alt': 'Short sleeve crochet cardigan',
  'desc': 'Stylish short sleeve crochet cardigan perfect for warmer weather. Handcrafted with premium yarn featuring intricate crochet patterns. Lightweight '
          'and breathable design. Perfect for layering over dresses or casual outfits. Contact for customized sizes and colors.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'sleeveless-cardigan',
  'name': 'Sleeveless Crochet Cardigan',
  'category': 'cardigans',
  'tags': ['cardigan', 'sleeveless', 'vest', 'ladies'],
  'price': 7200,
  'image': 'https://i.postimg.cc/Gm5j04DY/Crochet-sleeveless-Cardigan.png',
  'images': ['https://i.postimg.cc/Gm5j04DY/Crochet-sleeveless-Cardigan.png',
             'https://i.postimg.cc/y8bTqDRk/Crochet-sleeveless-Cardigan-Back.png',
             'https://i.postimg.cc/3xcZMkGD/Crochet-sleeveless-Cardigan-Front.png',
             'https://i.postimg.cc/vZNvR4ng/Crochet-sleeveless-Cardigan-Fabric.png'],
  'alt': 'Sleeveless crochet cardigan vest',
  'desc': 'Beautiful sleeveless crochet cardigan vest with elegant design. Handmade with soft, premium yarn. Perfect for layering in any season. Versatile '
          'style that works with casual and formal outfits. Comfortable fit and breathable material. Contact for customized sizes and colors.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'flower-crochet-cardigan',
  'name': 'Flower Crochet Cardigan',
  'category': 'cardigans',
  'tags': ['cardigan', 'floral', 'decorative', 'ladies'],
  'price': 7920,
  'image': 'https://i.postimg.cc/jSFhVDfP/Flower-Crochet-Cardigan.png',
  'images': ['https://i.postimg.cc/jSFhVDfP/Flower-Crochet-Cardigan.png',
             'https://i.postimg.cc/BnVCWjFm/Flower-Crochet-Cardigan-1.png',
             'https://i.postimg.cc/8z0b87vX/Flower-Crochet-Cardigan-2.png'],
  'alt': 'Flower crochet cardigan',
  'desc': 'Stunning flower crochet cardigan with beautiful floral embellishments. Handcrafted with premium yarn featuring delicate flower details. Unique and '
          'eye-catching design perfect for special occasions. Comfortable fit and artistic style. A true statement piece. Contact for customized sizes and '
          'colors.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'granny-square-cardigan',
  'name': 'Granny Square Cardigan',
  'category': 'cardigans',
  'tags': ['cardigan', 'granny square', 'vintage', 'ladies'],
  'price': 10800,
  'image': 'https://i.postimg.cc/3Nd2MWN7/Granny-square-cardigan-Front.jpg',
  'images': ['https://i.postimg.cc/3Nd2MWN7/Granny-square-cardigan-Front.jpg',
             'https://i.postimg.cc/L5njdh5m/Granny-square-cardigan-Fabric.jpg',
             'https://i.postimg.cc/90ry3z0W/Granny-square-cardigan-Side.jpg',
             'https://i.postimg.cc/qqz2fgqJ/Granny-square-cardigan-Sleeves.jpg',
             'https://i.postimg.cc/ht50FXm5/Granny-square-cardigan-Back.png'],
  'alt': 'Granny square cardigan',
  'desc': 'Classic granny square cardigan with vintage charm. Handmade with colorful premium yarn in traditional granny square pattern. Timeless design that '
          'never goes out of style. Comfortable, cozy, and full of character. Perfect for adding a retro touch to your wardrobe. Contact for customized sizes '
          'and colors.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'simple-crochet-cardigan',
  'name': 'Simple Crochet Cardigan',
  'category': 'cardigans',
  'tags': ['cardigan', 'simple', 'classic', 'ladies'],
  'price': 7920,
  'image': 'https://i.postimg.cc/8CfmTTBp/Simple-Crochet-Cardigan.png',
  'images': ['https://i.postimg.cc/8CfmTTBp/Simple-Crochet-Cardigan.png',
             'https://i.postimg.cc/mr1yTTN4/Simple-Crochet-Cardigan-Back.png',
             'https://i.postimg.cc/QMKJjjkh/Simple-Crochet-Cardigan-Fabric.png'],
  'alt': 'Simple crochet cardigan',
  'desc': 'Elegant simple crochet cardigan with clean, minimalist design. Handcrafted with soft premium yarn. Versatile and timeless style perfect for '
          'everyday wear. Comfortable fit and breathable material. Essential wardrobe piece that pairs with everything. Contact for customized sizes and '
          'colors.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'bow-tote-bag',
  'name': 'Bow Tote Bag',
  'category': 'handmade-bags',
  'tags': ['bag', 'tote', 'bow', 'ladies'],
  'price': 5760,
  'image': 'https://i.postimg.cc/DfqD52bz/Bow-Tote-Bags.png',
  'images': ['https://i.postimg.cc/DfqD52bz/Bow-Tote-Bags.png',
             'https://i.postimg.cc/05p3Z8Jj/Bow-Tote-Bags-Fabric.png',
             'https://i.postimg.cc/zDnMpJRG/Bow-Tote-Bags-Shoot.png'],
  'alt': 'Handmade bow tote bag',
  'desc': 'Elegant handmade tote bag with charming bow detail. Crafted with premium crochet yarn for durability and style. Spacious interior perfect for daily '
          'essentials. Features comfortable handles and sturdy construction. Perfect for shopping, work, or casual outings. Unique handmade quality with '
          'attention to detail.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'clutch-bag',
  'name': 'Clutch Bag',
  'category': 'handmade-bags',
  'tags': ['bag', 'clutch', 'evening', 'ladies'],
  'price': 3600,
  'image': 'https://i.postimg.cc/7PgcXxTf/Clutch-Bag.png',
  'images': ['https://i.postimg.cc/7PgcXxTf/Clutch-Bag.png',
             'https://i.postimg.cc/m2jnf8jr/Clutch-Bag-1.png',
             'https://i.postimg.cc/nhLPHBSM/Clutch-Bag-2.png'],
  'alt': 'Handmade clutch bag',
  'desc': 'Sophisticated handmade clutch bag perfect for special occasions. Beautifully crafted with premium materials and elegant design. Compact size ideal '
          'for essentials like phone, cards, and lipstick. Features secure closure and stylish appearance. Perfect for weddings, parties, or evening events. '
          'Handcrafted with love and precision.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'cross-body-bag',
  'name': 'Cross Body Bag',
  'category': 'handmade-bags',
  'tags': ['bag', 'crossbody', 'casual', 'ladies'],
  'price': 5760,
  'image': 'https://i.postimg.cc/K8YHZBpn/Cross-Body-Bag.png',
  'images': ['https://i.postimg.cc/K8YHZBpn/Cross-Body-Bag.png',
             'https://i.postimg.cc/QdMyX1YC/Cross-Body-Bag-Fabric.png',
             'https://i.postimg.cc/3xwcKmfR/Cross-Body-Bag-Model.png'],
  'alt': 'Handmade cross body bag',
  'desc': 'Stylish handmade cross body bag with adjustable strap. Crafted with premium crochet yarn for comfort and durability. Perfect size for everyday '
          'essentials with secure closure. Hands-free convenience ideal for travel, shopping, or daily activities. Trendy design with practical functionality. '
          'Handmade with care and quality craftsmanship.',
  'sizes': ['One Size'],
  'colors': ['Custom']},
 {'id': 'pink-tote-bag',
  'name': 'Pink Tote Bag',
  'category': 'handmade-bags',
  'tags': ['bag', 'tote', 'pink', 'ladies'],
  'price': 5760,
  'image': 'https://i.postimg.cc/FHnn1zwM/Pink-Tote-Bags.png',
  'images': ['https://i.postimg.cc/FHnn1zwM/Pink-Tote-Bags.png',
             'https://i.postimg.cc/fRggky1C/Pink-Tote-Bags-Fabric.png',
             'https://i.postimg.cc/T3HHh1BF/Pink-Tote-Bags-Shoot.png'],
  'alt': 'Handmade pink tote bag',
  'desc': 'Beautiful handmade pink tote bag with feminine charm. Crafted with soft premium yarn in lovely pink shade. Spacious and practical design perfect '
          'for daily use. Features sturdy handles and durable construction. Ideal for work, shopping, or casual outings. Handcrafted with attention to every '
          'detail.',
  'sizes': ['One Size'],
  'colors': ['Pink']},
 {'id': 'white-tote-bag',
  'name': 'White Tote Bag',
  'category': 'handmade-bags',
  'tags': ['bag', 'tote', 'white', 'ladies'],
  'price': 5760,
  'image': 'https://i.postimg.cc/W4FYZjPB/White-Tote-Bags.png',
  'images': ['https://i.postimg.cc/W4FYZjPB/White-Tote-Bags.png',
             'https://i.postimg.cc/Z5DD0n1t/White-Tote-Bags-Fabric.png',
             'https://i.postimg.cc/W4FYZjP9/White-Tote-Bags-Shoot.png'],
  'alt': 'Handmade white tote bag',
  'desc': 'Classic handmade white tote bag with timeless elegance. Crafted with premium crochet yarn in pristine white. Versatile design that complements any '
          'outfit. Spacious interior with comfortable handles. Perfect for everyday use, beach trips, or shopping. Handmade with quality and care.',
  'sizes': ['One Size'],
  'colors': ['White']}]
